HDRUK/hutch

docker-compose.yml
- Create docker-compose.yml file 
- [AB#59321](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/59321)
=> AB#59321: Add docker compose file for dev postgres service

app/LinkLiteManager/Data/Entities/ActivitySource.cs, app/LinkLiteManager/Data/Entities/SourceType.cs, app/LinkLiteManager/LinkLiteManager.csproj, app/LinkLiteManager/Program.cs, app/LinkLiteManager/appsettings.Development.json
- Use NPgSql instead of SqlServer in Program.cs
- Connect to Postgres db running on docker image
- Create two new Entities: ActivitySource &SourceType
- [AB#58551](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/58551)
- Need to do migrations locally after merging this branch
=> AB#58550: Setup configuration database

app/LinkLiteAgent/linkliteagent/config.py, app/LinkLiteAgent/linkliteagent/query.py, app/LinkLiteAgent/poetry.lock, app/LinkLiteAgent/pyproject.toml
Post results from an RQuest query to the hutch manager.
- [AB#58907](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/58907)
- [AB#59381](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/59381)
=> AB#58906: Internal Query Agent - Query Results

app/manager-frontend/src/api/activitysource.js, app/manager-frontend/src/components/ActivitySourceSummary.jsx, app/manager-frontend/src/pages/UserHome.jsx
added activity source list to home page ui
- [AB#62654](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/62654)
- [AB#62656](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/62656)
- [AB#62652](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/62652)
- [AB#62653](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/62653)
=> AB#62653: Activity source list

app/manager-frontend/src/api/activitysource.js, app/manager-frontend/src/components/ActivitySourceSummary.jsx, app/manager-frontend/src/components/forms/FormikSelect.jsx, app/manager-frontend/src/contexts/BackendApi.jsx, app/manager-frontend/src/pages/ActivitySource/index.jsx, app/manager-frontend/src/pages/ActivitySource/validation.js, app/manager-frontend/src/pages/UserHome.jsx, app/manager-frontend/src/routes/Root.jsx
Created the Activity source form page
- [AB#62658](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/62658)
=> AB#62658: Activity source form

app/LinkLiteManager/Controllers/ActivitySourceController.cs, app/LinkLiteManager/Services/ActivitySourceService.cs
- Get an activity source by ID
- [AB#63415](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/63415)
- [AB#63417](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/63417)
=> AB#62673: ActivitySource GET endpoint for getting a single ActivitySource by ID

app/LinkLiteManager/Controllers/ActivitySourceController.cs, app/LinkLiteManager/Services/ActivitySourceService.cs
-Add HttpDelete endpoint for ActivitySource
- [AB#63428](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/63428)
- [AB#63429](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/63429)
=> AB#62645: Add delete endpoint for ActivitySource

app/HutchManager/Models/CreateActivitySource.cs, app/manager-frontend/src/api/activitysource.js, app/manager-frontend/src/pages/ActivitySource/index.jsx, app/manager-frontend/src/pages/UserHome.jsx
Added frontend filtering to activity sources on the home page
- [AB#62655](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/62655)
=> AB#62655: sorting and filtering

app/HutchManager/Data/ApplicationDbContext.cs, app/HutchManager/Data/Entities/DataSource.cs, app/HutchManager/Models/DataSource.cs
Added DataSource entity
- [AB#64541](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64541)
- [AB#64538](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64538)
- [AB#64582](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64582)
=> AB#64541: Added DataSource entity

app/HutchAgent/hutchagent/ro_crates/query.py, app/HutchAgent/hutchagent/ro_crates/result.py, app/HutchAgent/tests/test_ro_crates.py
Python representation of RO-Crate result object (See #23).
- [AB#64678](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64678)
- [AB#64679](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64679)
=> AB#64149: Create Python classes for RO-Crates result models

app/manager-frontend/src/api/datasource.js, app/manager-frontend/src/components/DataSourceSummary.jsx, app/manager-frontend/src/components/DeleteModal.jsx, app/manager-frontend/src/contexts/BackendApi.jsx, app/manager-frontend/src/pages/ActivitySource/index.jsx, app/manager-frontend/src/pages/DataSource/list.jsx, app/manager-frontend/src/pages/UserHome.jsx, app/manager-frontend/src/routes/Root.jsx
Added Datasources page to the frontend
- [AB#64586](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64586)
- [AB#64587](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64587)
=> AB#64586: Datasources page

app/HutchManager/Controllers/AgentsController.cs
Added agents controller
- [AB#64571](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64571)
- [AB#64577](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64577)
- [AB#64578](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64578)
=> AB#64571: Added agents controller

app/HutchManager/Data/Entities/ActivitySource.cs, app/HutchManager/Data/Migrations/20220701145111_DataSources.Designer.cs, app/HutchManager/Data/Migrations/20220701145111_DataSources.cs, app/HutchManager/Models/ActivitySource.cs, app/manager-frontend/src/components/forms/FormikInput.jsx, app/manager-frontend/src/pages/ActivitySource/index.jsx
Added DataSource field to activity source
- [AB#64589](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64589)
- [AB#64588](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64588)
- [AB#64590](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64590)
Any further notes on changes not covered above. Delete if not required.
=> AB#64589: DataSource field

app/HutchManager/Controllers/AgentsController.cs, app/HutchManager/Models/AgentCheckinModel.cs, app/HutchManager/Models/DataSource.cs, app/HutchManager/Services/DataSourceService.cs
changed endpoint payload
- [AB#64594](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64594)
=> AB#64594: Endpoint Payload

app/HutchAgent/hutchagent/checkin.py, app/HutchAgent/hutchagent/main.py, app/HutchManager/Controllers/AgentsController.cs, app/HutchManager/Program.cs, app/HutchManager/Services/RquestPollingService.cs
- Temporarily remove authentication from `/api/agents/checkin`
- Add logging to `checkin.py:CheckIn.run`
- [AB#65941](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/65941)
- [AB#65943](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/65943)
- [AB#65942](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/65942)
=> AB#64561: Agent notifies Manager of target Data Source(s)

app/HutchManager/Controllers/ActivitySourceController.cs, app/HutchManager/Controllers/ResultsModifierController.cs, app/HutchManager/Data/ApplicationDbContext.cs, app/HutchManager/Data/Entities/ResultsModifier.cs, app/HutchManager/Models/ActivitySourceModel.cs, app/HutchManager/Models/CreateResultsModifier.cs, app/HutchManager/Models/LowNumberSuppressionParameters.cs, app/HutchManager/Models/ModifierTypeModel.cs, app/HutchManager/Models/ResultsModifierModel.cs, app/HutchManager/Program.cs, app/HutchManager/Services/ActivitySourceService.cs, app/HutchManager/Services/ResultsModifierService.cs
Added results modifier service
- [AB#65576](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/65576)
=> AB#65576: Results Modifier

app/manager-frontend/src/components/forms/FormikSelect.jsx, app/manager-frontend/src/helpers/dates.js, app/manager-frontend/src/pages/ActivitySource/index.jsx
Changed activity source datasource input to select options
- AB#6778
=> AB#6778: Datasource input

app/HutchManager/Models/RoundingConfiguration.cs
- Create RoundingConfiguration model
- [AB#65594](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/65594)
=> AB#65594:Add RoundingConfiguration model

app/HutchAgent/hutchagent/obfuscation.py, app/HutchAgent/tests/test_obfuscation.py
- Add the `rounding` function to `obfuscation.py`
- Requires a `ModifierType` with an `Id` of "Rounding" and the `Parameters` of a `ResultsModifier` that uses it looks like `{"nearest": 10}` (rounds a value to the nearest 10).
- [AB#54157](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/54157)
- [AB#65596](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/65596)
- [AB#65597](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/65597)
=> AB#53750: Rounding (agent)

app/manager-frontend/src/components/forms/FormikInput.jsx, app/manager-frontend/src/components/resultsmodifiers/ConfigureResultsModifierModal.jsx, app/manager-frontend/src/components/resultsmodifiers/LowNumberSuppressionParameters.jsx
- Change parameters to float instead of string value on form submit 
- [AB#69285](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/69285)
=> AB#69285: Test RoCrates end to end fix

app/HutchAgent/hutchagent/message_queue.py, app/HutchAgent/hutchagent/query.py, app/HutchAgent/poetry.lock, app/HutchAgent/pyproject.toml, app/HutchManager/appsettings.Development.json, app/HutchManager/appsettings.Production.json, scripts/load_tables.sql
- Use in-memory merging of simpler queries for RO-crates format queries.
- Set `"UseROCrates"` to default to true for dev and prod in the manager.
- Add script for uploading OMOP tables to database.
- AB#76012
- AB#76013
=> AB#76011: Use in-memory merging of simpler query results

app/HutchAgent/hutchagent/query_builders.py, app/HutchManager/Config/RquestTaskApiOptions.cs
- Implement concept lookups to decide which tables to query, instead of brute force querying all tables.
- AB#80133
- AB#80134
- AB#80135
- Also fix RQuest endpoint in manager
=> AB#78950: Concept lookups

docker-compose.prod.yml
- Replace links in docker compose Production file
- Replace links in main Docker compose file
- AB#79987
- AB#79988
- AB#79989
=> AB#78964: Update docs links in Docker Compose file

app/HutchManager/Services/ResultsModifierService.cs
Fixed a ResultsModifiers bug where a deletion of a Results Modifiers item doesn't trigger a reorder of the remaining items.
- For example, there are 3 or more modifiers and when users tries to delete the one that isn't the last one, the order remains incorrect.
- Fixed by calling a newly created method UpdateOrderOnDelete in delete, which updates the order based on deleted item.
- AB#82512
- AB#82524
- AB#82513
- AB#82523
=> AB#79975: ResultsModifiers bugfix

app/HutchManager/Controllers/AgentsController.cs, app/HutchManager/Models/ManageAgent.cs, app/HutchManager/Program.cs, app/HutchManager/Services/AgentService.cs
- Set up POST endpoint in AgentsController, for creating new Agents
- Create ManageAgent model
- AB#84827
- AB#84826
=> AB#84783: Set up POST endpoint for Agents

app/HutchManager/Controllers/AgentsController.cs, app/HutchManager/Program.cs, app/HutchManager/Services/AgentService.cs, app/manager-frontend/src/pages/Agent/list.jsx
- Add a Delete Action to the Actions button for Agents
- DELETE method for `/agents` API endpoint
- Delete Button triggers a modal (copy Activity Source style)
- AB#84790
- AB#84795
- AB#84792
- AB#84796
=> AB#84784: Deleting Agents

app/HutchManager/Controllers/AccountController.cs, app/HutchManager/Models/Account/SetAccountActivateModel.cs, app/HutchManager/Models/User/UserModel.cs, app/manager-frontend/src/api/user.js, app/manager-frontend/src/components/users/UserSummary.jsx, app/manager-frontend/src/pages/User/list.jsx
- **Add User Summary Card component**
- **Add Delete Action to the Actions button menu**
- **Delete Action triggers confirmation modal**
- **Add Filterable List of Summary Cards for Users**
- Update `UserModel` to include users `AccountConfirmed` status and `FullName` in `Users` GET method in `UsersController`
- **Add an item to User Card Actions that allows admins to generate a new link for a User**
_**Account inactive** (Display Generate activation link button)_
_**Account active** (Prevent displaying delete button for currently logged in user_) 
_**Generate activation link modal**_
- **Update user `FullName` when activating the user account (previously only `Password` and `AccountConfirmed` was updated).**
- Create new models `SetUseAccountModel` and `AnonymousSetUserAccountModel` for …
=> AB#85291: User Summary Card, Filterable Users List, Deleting Users and Generate activation link on the summary card

app/HutchManager/Config/RegistrationOptions.cs, app/HutchManager/Constants/FeatureFlags.cs, app/HutchManager/Constants/RegistrationOptions.cs, app/HutchManager/Constants/UserRegistrationOptions.cs, app/HutchManager/Controllers/AccountController.cs, app/HutchManager/Middleware/ConfigCookieMiddleware.cs, app/HutchManager/Models/ConfigCookieModel.cs, app/HutchManager/Program.cs, app/HutchManager/Services/UserService.cs, app/HutchManager/appsettings.Development.json, app/HutchManager/appsettings.Production.json, app/manager-frontend/src/components/NavBar.jsx, app/manager-frontend/src/pages/account/Login.jsx, app/manager-frontend/src/pages/account/Register.jsx, website/docs/users/getting-started/configuration/manager.md
- Switch from AllowFreeRegistration Feature Flag, to UserAccounts: Registration: "free/limited/disabled"
- if registration is free/limited settings have the old functionality of AllowFreeRegistration: true/false
- if registration is disabled, remove links to register page from Login & NavBar + register page redirects to 404 + register post endpoint returns 404
- AB#87627
- AB#87628
=> AB#85308: Change Registration configuration

app/manager-frontend/public/locales/dev/core.json, app/manager-frontend/src/components/forms/UsernameField.jsx, app/manager-frontend/src/pages/account/Login.jsx, app/manager-frontend/src/pages/account/Register.jsx
- Replace Email login with Username Login
- AB#89061
=> AB#89060: Register new user by username

.github/workflows/publish.agent-wheel.yml, .github/workflows/release.hutch-agent.yml, .github/workflows/version.hutch-agent.yml
- Disable automatic agent building for now.
- AB#89728
- AB#92795
=> AB#89727: Hatch updates

website/docs/devs/external-systems/bcos/distribution-queries.md
Corrections to the documentation about distribution queries
- AB#80401
=> AB#80380: Document Distribution Query Process

app/rquest-omop-agent/Dockerfile
- Dockerfile for `rquest-omop-agent`
- AB#94308
- AB#94309
- AB#94310
=> AB#93973: Build Docker Image for One Shot Agent

.github/workflows/publish.rquest-omop-agent.yml, .github/workflows/release.rquest-omop-agent.yml
- Workflow to publish a timestamped docker image of the "one-shot" rquest omop agent
- Workflow for stable release of dockerised agent
- AB#94473
- AB#94474
=> AB#94466: rquest-omop-agent docker image github workflows

website/docs/devs/external-systems/wfexs/config.md, website/docs/devs/external-systems/wfexs/index.md, website/docs/devs/external-systems/wfexs/installing-wfexs.md, website/docs/devs/external-systems/wfexs/running-wfexs.md
Documentation for Hutch developers after experimenting with WfExS.
* Installation
* Configuration
* Running
- AB#94497
- AB#94498
- AB#94486
- AB#94487
- AB#94489
=> AB#95986: Run through WfExS with output ro-crate

Hutch.sln, app/HutchAgent/HutchAgent.csproj, app/HutchAgent/Program.cs
- Create new HutchAgent app and add it to the project solution
- AB#97875
- AB#97877
- AB#97876
=> AB#97520: Create new .NET app project (console app)

lib/ROCrates.Net.Tests/TestDataset.cs
Same problem as #163.
- AB#99134
- AB#99135
=> AB#98841: Dataset unit tests fail

lib/ROCrates.Net.Tests/TestEntity.cs, lib/ROCrates.Net/Models/Entity.cs, lib/ROCrates.Net/Models/TestDefinition.cs, lib/ROCrates.Net/ROCrate.cs
- Create a `TestDefinition` class and associated builder method in `ROCrate`.
- Tidy up unit test suite relating to changes to the relevant test suite. (based on advice from @MoizIqbal97 in #162)
- AB#99301
- AB#99303
=> AB#99293: TestDefinition class

lib/ROCrates.Net/Models/TestService.cs
`TestService` class
- AB#99449
=> AB#99291: TestService class

lib/ROCrates.Net/Models/TestInstance.cs, lib/ROCrates.Net/ROCrate.cs
Create `TestInstance` class and add associated builder method to `ROCrate`.
- AB#99454
- AB#99455
=> AB#99290: TestInstance class

lib/ROCrates.Net.Tests/TestComputerLanguage.cs, lib/ROCrates.Net/Models/ComputerLanguage.cs
Create `ComputerLanguage` class.
- AB#99484
- AB#99485
=> AB#99294: ComputerLanguage class

workflows/hello-world-wf.cwl, workflows/hello-world.cwl, workflows/rquest-oneshot.cwl, workflows/rquest-oneshotx86.cwl, workflows/sec-hutch.cwl, workflows/sec-hutchx86.cwl
- Add workflow directory with rquest-omop-worker cwl workflows
=> Add .cwl workflows

website/docs/devs/external-systems/wfexs/installing-wfexs.md, website/docs/devs/external-systems/wfexs/running-test-workflow.md, website/docs/devs/external-systems/wfexs/running-wfexs.md
- Update wfexs gotchas to include python-dxf version
- Add config and instructions to run rquest-omop-worker
- AB#96874
- AB#94499
- AB#94496
- AB#99505
- AB#99506
=> AB#94492: Update documentation site to cover wfexs workflow running

app/HutchAgent/HutchAgent.csproj, app/HutchAgent/Models/WorkflowTriggerOptions.cs, app/HutchAgent/Program.cs, app/HutchAgent/Properties/launchSettings.json, app/HutchAgent/Services/WorkflowTriggerService.cs, app/HutchAgent/appsettings.json
- Create WorkflowTriggerService to execute WfExS
- Create WorkflowTriggerOptions Model for config details
- AB#97891 
- AB#97888 
- AB#97886 
- AB#97884 
- AB#97887
=> AB#97882: HutchAgent to execute wfexs

app/rquest-omop-worker/scripts/worker.py
Change --body input to be a json file instead of string
- AB#101349
=> AB#97892: Rquest worker json input

workflows/rquest-oneshot.cwl, workflows/rquest-oneshotx86.cwl, workflows/sec-hutch.cwl, workflows/sec-hutchx86.cwl
Update workflows to work with new rquest-omop-worker, expecting body input to be a JSON file
- AB#97896
=> AB#97892: Update Rquest worker workflow

website/docs/devs/external-systems/wfexs/running-test-workflow.md
Document workflow_id in stage file expecting RO-Crate if given an absolute path
- AB#99532
=> AB#99532: Note for Wfexs stage file

workflows/inputs/rquest-query.json
Add input JSON
- AB#99512
Any further notes on changes not covered above. Delete if not required.
=> AB#99507: Input json for workflow

ansible/inventory.ini, ansible/playbook.yml, ansible/playbooks/install-docker.yml, ansible/playbooks/set-up-vm.yml, ansible/playbooks/wfexs.yml, website/docs/devs/external-systems/wfexs/wfexs-dev-env.md
Ansible plays to set up an environment to run WfExS.
- AB#103426
- AB#102490
=> AB#102489: Ansible for Wfexs setup

app/HutchAgent/Config/MinioOptions.cs, app/HutchAgent/HutchAgent.csproj, app/HutchAgent/Program.cs, app/HutchAgent/Services/MinioService.cs
Add a service to `HutchAgent` to upload a ro-crate to a s3 bucket.
- AB#104229
- AB#104230
- AB#104232
=> AB#104228: Upload the modified crate (including results) to target (S3)

app/HutchAgent/HutchAgent.csproj, app/HutchAgent/Services/WatchFolderService.cs, app/HutchAgent/Services/WorkflowTriggerService.cs
- Create scope for WfexsJobService to resolve runtime exceptions
- AB#105816
=> AB105814: Create scope in HostedService for WfexsJobService

app/HutchAgent/Config/WatchFolderOptions.cs
- Change PollingInterval to int from double
- AB#104722
=> AB#104721:Change polling interval from double to int

lib/ROCrates.Net.Tests/TestRoCrate.cs, lib/ROCrates.Net/ROCrate.cs
Save an RO-Crate as either a directory or a .zip file.
- AB#98460
- AB#98461
- AB#107545
- AB#107544
=> AB#98892: Saving RO-Crates

app/HutchAgent/Constants/FeatureFlags.cs, app/HutchAgent/Controllers/JobsController.cs, app/HutchAgent/HutchAgent.csproj, app/HutchAgent/Program.cs, app/HutchAgent/Services/WorkflowTriggerService.cs
- Add FeatureFlag UseFiveSafesCrate
- Small fix on metadata not found check
- AB#108969
- AB#108970
- AB#108971
=> AB#108968: Introduce a feature flag for job crates to use "5 Safes" profile

app/HutchAgent/HostedServices/JobPollingHostedService.cs, app/HutchAgent/Services/MinioService.cs, app/HutchAgent/Services/WorkflowTriggerService.cs
- Fix Path Names for minio upload to work
- AB#111744
- AB#111745
- AB#111746
- AB#111747
=> AB#111743:Fix minio upload

ansible/playbooks/set-up-vm.yml, ansible/playbooks/wfexs.yml, website/docs/devs/external-systems/wfexs/wfexs-dev-env.md, website/docs/users/getting-started/configuration/docker-hub-spoof.md
- Improve advice for setting up wfexs VM.
- Advise users on use of podman.
- Tidy up ansible scripts.
- AB#119209
=> AB#115986: Update tre setup docs

app/HutchAgent/Services/WorkflowTriggerService.cs
- Fix wfexs triggering process
- AB#120710
=> AB#120709: Change back to using bin/bash process

app/HutchAgent.Tests/TestCrateMergeService.cs, app/HutchAgent/Data/Entities/WfexsJob.cs, app/HutchAgent/HostedServices/JobPollingHostedService.cs, app/HutchAgent/Migrations/20230814125754_AddStartTimeEndTime.Designer.cs, app/HutchAgent/Migrations/20230814125754_AddStartTimeEndTime.cs, app/HutchAgent/Migrations/20230816101219_ChangeToDateTimeOffset.Designer.cs, app/HutchAgent/Migrations/20230816101219_ChangeToDateTimeOffset.cs, app/HutchAgent/Services/CrateMergerService.cs, app/HutchAgent/Services/WfexsJobService.cs
- Merged crate now has its metadata updated to show:
- start and end times for the workflow run
- result files on the create action
- error status on create action
- AB#109797
- AB#109799
- AB#109798
- AB#109800
- AB#109801
- AB#109803
=> AB#109768: Handle Workflow Execution failures?

app/HutchAgent/Config/WfexsTriggerOptions.cs, app/HutchAgent/HostedServices/QueuePollingHostedService.cs, app/HutchAgent/Program.cs, app/HutchAgent/Services/ExecuteActionHandler.cs, app/HutchAgent/Services/WorkflowFetchService.cs, app/HutchAgent/Services/WorkflowFetchingService.cs, app/HutchAgent/Services/WorkflowTriggerService.cs
- Create new `WorkflowFetchService` for fetching the workflow RO-Crate, validating it and creating the downloadAction
- Remove obsolete code from `WorkflowTriggerService` 
- Fix stage file paths in `TriggerWfexs` method
=> AB#124760: Refactor fetching workflows and execution

app/HutchAgent/Services/CrateService.cs
Remove a step to update the RO-Crate's CreateAction from `CrateService.UpdateMetadata`. This can be handled by `CrateService.UpdateCrateActionStatus` from #232.
- AB#124929
- AB#125113
Files being added to the `metadata.json` was already added by #227
=> AB#115174: Results merging - workflow outputs metadata

app/HutchAgent/Services/CrateService.cs, app/HutchAgent/Services/ExecuteActionHandler.cs, app/HutchAgent/Services/WorkflowFetchService.cs
- Create `CheckAssessActions` method for checking AssessAction exists and is set to completed
- Add it as a step in `ExecuteActionHandler`
- AB#125080
=> AB#124142: Hutch agent should confirm that pre-execution assessAction exists or is completed

app/HutchAgent/Constants/FeatureFlags.cs
- Remove `UseFiveSafesCrate` feature flag
- AB#125563
=> AB#124146: Remove feature flag

.github/workflows/publish.HutchAgent.yml, app/HutchAgent/HutchAgent.csproj, app/HutchAgent/Program.cs
This PR adds a "Publish" workflow, to produce binary outputs of any merge to `main`, and ensure Unit Tests pass against those binary builds.
- No functional code changes
=> AB#126516: Publish workflow

.github/workflows/release.HutchAgent.yml
This PR adds a manually triggered GitHub Release workflow, which makes a release from a given Publish Binaries workflow run.
- no new functional code added
=> AB#126516: Release workflow

ansible/playbooks/wfexs.yml
Pin WfExS installation via Ansible to a known good commit, rather than using `main`.
- AB#129942
- AB#129943
- Closes #
- Not changing tested code or making new testable code
=> AB#129941: Pin Wfexs to known working commit

app/HutchAgent/Config/MinioOptions.cs, app/HutchAgent/Controllers/JobsController.cs, app/HutchAgent/Extensions/ServiceCollectionExtensions.cs, app/HutchAgent/Models/DatabaseConnectionDetails.cs, app/HutchAgent/Models/FileStorageDetails.cs, app/HutchAgent/Models/SubmitJobModel.cs, app/HutchAgent/Program.cs, app/HutchAgent/Services/ActionHandlers/FetchAndExecuteActionHandler.cs, app/HutchAgent/Services/ActionHandlers/InitiateEgressActionHandler.cs, app/HutchAgent/Services/FinaliseActionHandler.cs, app/HutchAgent/Services/Hosted/JobPollingHostedService.cs, app/HutchAgent/Services/JobLifecycleService.cs, app/HutchAgent/Services/MinioStoreService.cs, app/HutchAgent/appsettings.Development.json, website/docs/getting-started/configuration/agent.md
This PR amends the Submit endpoint for the Jobs API to reflect agreed changes in the interface. It also reworks Crate Fetching to support MinIO as a source.
It currently requires direct MinIO Access credentials to be supplied; in future we will support acquiring temporary credentials via an OIDC token.
Also updated configuration docs to reflect changed Options Models and Section names.
- no new unit testable code added - all refactoring or integration.
=> AB#129865: Job submission api changes

ansible/playbooks/wfexs.yml
Change Ansible playbook to use a fork of WfExS. Bypasses a hardcoded github/gitlab check that prevents using other git sources.
- AB#130252
- AB#130254
- AB#130253
- Closes #
- No changes to tested code.
=> AB#130251: Use UoN wfexs fork

app/HutchAgent.Tests/MinioStoreServiceTests/TestUploadFilesRecursively.cs, app/HutchAgent/Config/ControllerApiOptions.cs, app/HutchAgent/HutchAgent.csproj, app/HutchAgent/Models/ControllerApi/FilesReadyForReviewRequest.cs, app/HutchAgent/Models/FileForReviewModel.cs, app/HutchAgent/Program.cs, app/HutchAgent/Services/ActionHandlers/InitiateEgressActionHandler.cs, app/HutchAgent/Services/ControllerApiService.cs, app/HutchAgent/Services/FiveSafesCrateService.cs, app/HutchAgent/Services/JobLifecycleService.cs, app/HutchAgent/Services/MinioStoreService.cs, app/HutchAgent/Services/WorkflowFetchService.cs, app/HutchAgent/Services/WorkflowTriggerService.cs
This PR adds functionality to the `InitiateEgress` ActionHandler:
- relevant API calls to TRE Controller API are now implemented
- InitiateEgress performs more of its metadata update responsibilities now
- Added some info logging
Also some improvements
- move all HTTP calls to use Flurl
- Fixed Recursive File uploads to return a list of uploaded files
- Unit Tests for the above
- _please replace this line with details on why tests have not been included_
=> AB#126520: Egress bucket api call

app/HutchAgent/Controllers/JobsController.cs, app/HutchAgent/Models/Wfexs/WorkflowStageFile.cs, app/HutchAgent/Services/ActionHandlers/ExecuteActionHandler.cs, app/HutchAgent/Services/ActionHandlers/FinalizeActionHandler.cs, app/HutchAgent/Services/JobLifecycleService.cs, app/HutchAgent/Services/WorkflowFetchService.cs, app/HutchAgent/Services/WorkflowTriggerService.cs
This PR Adds Status Reporting for the `Execute` and `Finalize` ActionHandlers, rounding out reporting of all current statuses end to end. 🎉
It also does some tidy up / fixing of path usage.
- No testable code added or modified
=> AB#130322: Status updates

.config/dotnet-tools.json, .github/workflows/build.docs-website.yml, .github/workflows/deploy.docs-website.yml, pnpm-lock.yaml, website/package.json, website/src/pages/swagger.tsx
This PR publishes the swagger spec independently of the app and hosts it in the docs website.
- no testable code added or modified
=> AB#130446: Standalone swagger in docs website

app/HutchAgent/Constants/ApprovalType.cs, app/HutchAgent/Controllers/JobsController.cs, app/HutchAgent/Models/ApprovalResult.cs, app/HutchAgent/Services/ActionHandlers/FinalizeActionHandler.cs, app/HutchAgent/Services/FiveSafesCrateService.cs, app/HutchAgent/Services/JobLifecycleService.cs
Create an endpoint for submitted approval results from the TRE controller.
- AB#130098
- Closes #
- _please replace this line with details on why tests have not been included_
=> AB#130098: Approval Endpoint

app/HutchAgent/Services/FileSystemResultsStoreService.cs, app/HutchAgent/Services/WorkflowTriggerService.cs
Removing stuff that was marked obsolete, now that we're through significant refactoring.
- no testable code added or modified
=> AB#125570: resolving obsolescence

app/HutchAgent.Tests/TestFiveSafesCrateService.cs, app/HutchAgent/Config/CratePublishingOptions.cs, app/HutchAgent/Config/WorkflowTriggerOptions.cs, app/HutchAgent/Constants/FeatureFlags.cs, app/HutchAgent/Constants/JobStatuses.cs, app/HutchAgent/Models/Wfexs/WorkflowStageFile.cs, app/HutchAgent/Program.cs, app/HutchAgent/Services/ActionHandlers/FetchAndExecuteActionHandler.cs, app/HutchAgent/Services/ActionHandlers/FinalizeActionHandler.cs, app/HutchAgent/Services/ActionHandlers/InitiateEgressActionHandler.cs, app/HutchAgent/Services/FiveSafesCrateService.cs, app/HutchAgent/Services/JobLifecycleService.cs, app/HutchAgent/Services/MinioStoreService.cs, app/HutchAgent/Services/WorkflowFetchService.cs, app/HutchAgent/Services/WorkflowTriggerService.cs, website/docs/getting-started/configuration/agent.md
This PR makes numerous miscellaneous fixes to allow Hutch to run through end-to-end in Standalone mode (i.e. without a TRE Controller API).
With the correct wfexs configuration, this end-to-end process is successful.
Wfexs work is in progress but currently, an internet-enabled host machine using singularity and the latest uon-drs fork of wfexs will work.
- no testable code added or modified.
=> AB#105505: Hutch Run fixes

DummyControllerApi/Controllers/SubmissionController.cs, DummyControllerApi/DummyControllerApi.csproj, DummyControllerApi/Models/FinalOutcomeRequestModel.cs, app/HutchAgent/Models/ControllerApi/FinalOutcomeRequest.cs, app/HutchAgent/Services/ActionHandlers/FinalizeActionHandler.cs, app/HutchAgent/Services/ControllerApiService.cs
This PR adds the `FinalOutcome` TRE Controller API call to the FinalizeAction, and also the the Dummy Controller API.
- integration code only
=> AB#131714: Controller api final outcome

app/HutchAgent/Models/Wfexs/WorkflowStageFile.cs, app/HutchAgent/Services/WorkflowTriggerService.cs
- Adds the environment variables to the stage files under `environment` instead of `params`
- adding dictionary to class object, not sure this is complex enough to test
=> AB#130480: Set DB settings as env vars in stage file

app/DummyControllerApi/Config/EgressBucketDetailsOptions.cs, app/DummyControllerApi/Controllers/SubmissionController.cs, app/DummyControllerApi/Models/EgressBucketResponseModel.cs, app/DummyControllerApi/Models/HutchApprovalRequestModel.cs, app/DummyControllerApi/Services/EgressApprovalHostedService.cs, app/HutchAgent/Controllers/JobsController.cs, app/HutchAgent/MappingProfiles/MinioOptionsProfile.cs, app/HutchAgent/Models/ApprovalResult.cs, app/HutchAgent/Models/ControllerApi/GetOutputBucketInfoReponse.cs, app/HutchAgent/Models/FileStorageDetails.cs, app/HutchAgent/Services/ActionHandlers/FinalizeActionHandler.cs, app/HutchAgent/Services/ActionHandlers/InitiateEgressActionHandler.cs, app/HutchAgent/Services/ControllerApiService.cs
This PR aligns Hutch with some Controller API changes
- just changing interfaces
=> AB#132881: Controller api changes

app/HutchAgent/Config/PathOptions.cs, app/HutchAgent/Config/WorkflowTriggerOptions.cs, app/HutchAgent/Constants/ContainerEngineType.cs, app/HutchAgent/Models/DatabaseConnectionDetails.cs, app/HutchAgent/Models/Wfexs/WorkflowStageFile.cs, app/HutchAgent/Services/WorkflowTriggerService.cs, website/docs/getting-started/configuration/agent.md
- Platform independently set the working directory for running WfExS to a subdirectory in the user's home directory.
- Default the WfExS related working directories to be in the user's home directory, in line with the ansible install.
- Converted the `ContainerEngine` field in `WorkflowTriggerOptions` to an `enum`.
- Update agent docs to show default values for fields (unless otherwise specified).
- Closes #
- no tests altered, no new code.
=> AB#129760: Working Directory Path

ansible/playbooks/files/docker-compose.yml, app/HutchAgent/Services/ControllerApiService.cs, app/HutchAgent/Services/MinioStoreService.cs, app/HutchAgent/Services/OpenIdIdentityService.cs
- refresh tokens using openid and keycloak
- _please replace this line with details on why tests have not been included_
=> AB#131632:Auth token refresh

ansible/playbooks/files/docker-compose.yml, website/docs/external-systems/keycloak/index.md, website/docs/getting-started/configuration/agent.md
Add additional advice for setting up keycloak as the OIDC provider for MinIO with hutch.
- Closes #
- no code updates
=> AB#134752: Keycloak setup

app/HutchAgent/Services/OpenIdIdentityService.cs, test/HutchAgent.Tests/FileSystemUtilityTests/TestSelectivelyDelete.cs
Add the client secret to the token refresh requests. Also fix a compiler warning in the tests
- _please replace this line with details on why tests have not been included_
=> AB#135004: Missing client secret in token refresh
