HDRUK/hutch

app/HutchManager/Dto/RquestQueryResult.cs
app/HutchManager/Dto/RquestQueryTask.cs
app/HutchManager/Services/RquestPollingService.cs
app/HutchManager/Services/RquestTaskApiClient.cs

- Change TaskId/taskId/task to JobId/jobId/job
- Get uuid from Rquest instead of task_id
- Replace collectionid with resourceID
- Send ActivitySource Id to queue instead of CollectionId
- [AB#64557](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/64557)

AB#64557: Manager terminology updates

---

app/HutchAgent/hutchagent/message_queue.py
app/HutchAgent/hutchagent/query.py
app/HutchAgent/tests/test_query.py

- Reverted #56
- Re-refactored RQuest query related classes in `HutchAgent/hutchagent/query.py`
- Recovers lost numeric and time rule functionality
- RQuest callback in `message_queue.py` accommodates new RQuest format and sends results to `api/results`
- [AB#67667](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/67667)
- [AB#67668](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/67668)
- [AB#67691](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/67691)
- [AB#67669](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/67669)

AB#67666: Revert AB#62680

---

app/HutchAgent/hutchagent/db_logging.py
app/HutchAgent/tests/test_db_logging.py
app/HutchManager/Data/Entities/Logs.cs
app/HutchManager/Data/Migrations/20220715122118_20220715_rename_logs_to_Logs.Designer.cs
app/HutchManager/Data/Migrations/20220715122118_20220715_rename_logs_to_Logs.cs
app/HutchManager/Data/Migrations/20220718113123_RemoveUnderScoreFromMessageTemplate.Designer.cs
app/HutchManager/Data/Migrations/20220718113123_RemoveUnderScoreFromMessageTemplate.cs
app/HutchManager/appsettings.Development.json

- Make the names of the Logs table code match between the Manager and Agent.
- Make the order of columns match.
- Make migrations for the manager.
- Change the Serilog setting point to the new table name.
- [AB#67966](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/67966)
- [AB#67967](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/67967)
- [AB#67968](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/67968)
- [AB#67969](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/67969)

AB#67849: Get the agent and the manager to use the same log db

---

app/HutchManager/Services/ResultsModifierService.cs
app/manager-frontend/src/components/ConfigureResultsModifierModal.jsx
app/manager-frontend/src/components/forms/FormikSelect.jsx

Fixed results modifier functionality on the frontend with formikSelect.
- Error was being thrown when trying to convert activity source entity from results modifier to an activity source model because the type was not being included. Now fixed by including type for results modifier activity sources
- formik values of Activity Source and Type in formikSelect were being set as string values instead of objects which was causing a bug in displaying the changes when editing those values and in submitting those values. Fixed by editing formikSelect to be able to handle objects
- [AB#67952](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/67952)

AB#67952: ResultsModifier Bugfix

---

app/HutchAgent/hutchagent/entities.py
app/HutchAgent/hutchagent/message_queue.py
app/HutchAgent/hutchagent/query.py
app/HutchAgent/hutchagent/ro_crates/group.py
app/HutchAgent/tests/test_query.py
app/HutchAgent/tests/test_ro_crates.py

- Introduce query builder classes for RQuest and RO-Crates queries which brute force query all the tables.
- Use the query builders in callbacks.
- Queries join subqueries to other tables besides `Person`.
- [AB#68172](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/68172)
- [AB#68362](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/68362)
- [AB#69514](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/69514)
- [AB#69580](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/69580)
- [AB#68171](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/68171)
- …

AB#62642: Internal Query Agent - joining to more OMOP tables

---

app/HutchAgent/.dockerignore
app/HutchAgent/Dockerfile
app/HutchAgent/hutchagent/main.py
app/HutchAgent/hutchagent/message_queue.py
app/HutchAgent/poetry.lock
app/HutchAgent/pyproject.toml

- Created a `Dockerfile` for the agent.
- Resolved a dependency issue with `psycopg2-binary` vs `psycopg2`.
- `psycopg2-binary` is now a dev dependency so the agent runs locally on Macs with M1 chips.
- `psycopg2` is the prod package that works inside the container.
- Added `MSG_QUEUE_HOST` environment variable, which defaults to `localhost`.
- [AB#72092](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/72092)
- [AB#72093](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/72093)

AB#69934: Dockerise agent

---

.github/workflows/publish.agent-docker.yml
app/HutchAgent/Dockerfile

Workflow to build hutchagent docker image as an artifact.
- appears as `action_image_artifact_hutchagent_latest` since the name isn't configurable in the workflow 👎 
- [AB#75072](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/75072)
- [AB#75073](https://dev.azure.com/UniversityOfNottingham/bd2de5ba-2a41-4bdc-a444-61e6b706132a/_workitems/edit/75073)

AB#75070: CI to build Agent docker image artefact

---

app/manager-frontend/src/components/DeleteModal.jsx
app/manager-frontend/src/components/NavBar.jsx
app/manager-frontend/src/components/resultsmodifiers/ResultsModifiers.jsx
app/manager-frontend/src/pages/ActivitySource/index.jsx
app/manager-frontend/src/pages/UserHome.jsx
app/manager-frontend/src/themes/theme.js

- Change DeleteModal body text so both instances match when deleting an ActivitySource, display name instead of numeric ID, removed the close button since it already has Cancel button
- Add Cancel buttons to both Edit and Create forms in case the user needs to navigate back without having to click on nav bar link
- Switch the position of the delete button to the the bottom of the form, so cancel can stay on top for both forms
- Change the headers to match, colour and display ActivitySource name in the header for Edit form
- Change button text to be shorter "Create" & "Save"
- Set default width to match the main page layout
- AB#77098
- AB#77148
- AB#77099

AB#67773: Update Activity Source forms

---

app/manager-frontend/src/components/NavBar.jsx
app/manager-frontend/src/pages/account/Login.jsx
app/manager-frontend/src/pages/account/Register.jsx
app/manager-frontend/src/pages/account/RequestPasswordReset.jsx
app/manager-frontend/src/pages/account/ResetPassword.jsx
app/manager-frontend/src/routes/Root.jsx

- Add the color Hutch logo to the login, registration and password reset pages.
**Login page**
**Registration page**
**Password reset page**
- Update the index route
- Display navbar items (collectively) based on pathname. For example, hide nav bar items in **login** page but display when users log in.
- AB#79993
- AB#79994
- AB#79995

AB#79982: Manager homepage

---

app/HutchManager/Data/UserDataSeeder.cs
app/HutchManager/Models/Account/LoginModel.cs
app/HutchManager/Program.cs

Hutch should have an out the box "super admin" account which is determined by configuration, and doesn't require registration or an email address.
- Copy User DataSeeder from DECSYS
- Amend Configuration keys for Root Admin account credentials
- Fix User type inside the DataSeeder
- Run UserData seeding in Program.cs
- Create custom validation attribute to validate valid email and username when users tries to log in.
- AB#83742
- AB#83743
- AB#83744
- AB#83745
- AB#83747

AB#83741: SuperAdmin

---

app/HutchManager/Controllers/AgentsController.cs
app/HutchManager/Models/AgentCheckinModel.cs
app/HutchManager/Services/DataSourceService.cs

- Modify 'api/agents/checkin' endpoint to link DataSources and Agents on check in
- Allows multiple agents to check in to multiple datasources
- If no new agents are checking in, only updates the LastCheckIn field
- AB#85561
- AB#85562

AB#85558: Update CheckIn endpoint to link DataSources with Agents

---

app/HutchManager/Constants/ClientRoutes.cs
app/HutchManager/Controllers/AccountController.cs
app/HutchManager/Controllers/UserController.cs
app/HutchManager/Data/Entities/Identity/ApplicationUser.cs
app/HutchManager/Data/Migrations/20221205222146_Extend_IdentityUser.Designer.cs
app/HutchManager/Data/Migrations/20221205222146_Extend_IdentityUser.cs
app/HutchManager/Models/Account/TokenLinkModel.cs
app/HutchManager/Models/Account/UserActivationTokenModel.cs
app/HutchManager/Services/TokenIssuingService.cs

- Add new column `AccountConfirmed` to store account activation status
- **Add `GenerateAccountActivationLink` method to `TokenIssuingService`**
- Add attribute `Authorize' to ensure only authenticated users can action this request.
- Generate an user activation link that can be passed to the user. 
- The link takes user to `account/activate` page where user can set password and activate their account.
- **Activate Account backend POST route in `AccountController`**
- Validate token when it receives a request to activate user account with a payload (includes `Token`, `Password` and `Userid`)
- Then, hash the password and update user `PasswordHash` and `AccountConfirmed` status to mark account as active
- AB#85317
- AB#85320
- AB#87488

AB#85317: Add POST method to generate user account activation link and complete account activation

---

app/HutchManager/Controllers/AccountController.cs
app/HutchManager/Models/Account/UserPasswordResetTokenModel.cs
app/HutchManager/Services/TokenIssuingService.cs
app/manager-frontend/public/locales/dev/core.json
app/manager-frontend/src/api/user.js
app/manager-frontend/src/components/users/UserSummary.jsx
app/manager-frontend/src/pages/account/ResetPassword.jsx

- Add `GeneratePasswordResetLink` to `TokenIssuingService`
- Add `Reset Password` Action to the Actions button menu
- Reset Password action displays modal containing the new link (and a copy button)
_Display generate password reset button only if the user is active_
_Password Reset modal_
- Update `AccountController` Activate POST method 
- AB#85330
- AB#85331
- AB#85332
- AB#85333

AB#85294: Admin Password Reset link (re)generation

---

app/HutchManager/Extensions/ServiceCollectionExtensions.cs
website/docs/users/getting-started/configuration/manager.md

- Fix bug in manager build where a default job queue is required in the configuration. Defaults to "RabbitMQ"
- AB#89732
- AB#89736
- AB#89737
- AB#89733
- AB#89738
- AB#89739

AB#89730: Migrations can't be generated due to no default queue config

---

app/rquest-omop-agent/pyproject.toml
app/rquest-omop-agent/rquest_omop_agent/query_solvers.py
app/rquest-omop-agent/scripts/agent.py
lib/hutch_utils/obfuscation.py

- One shot app is independent of the Manager.
- The app takes the body of a query and optionally some results modifiers, both in JSON format, and solves the query.
- The output is saved to disk. The user may optionally give a path to save the file to.
- AB#93965
- AB#93966
- AB#93967
- AB#93968
- AB#94032
- AB#93969
- new usage help message:
```shell
usage: rquest-omop-agent [-h] --body BODY [-a] [-d] [-o OUTPUT] [-m RESULTS_MODIFIERS]
This program takes a JSON string containing an RQuest query and solves it.
options:
-h, --help            show this help message and exit
--body BODY           The JSON string containing the query
-a, --availability    The query is a availability query
-d, --distribution    The query is a distribution query
-o OUTPUT, --output OUTPUT
The path to the output …
```

AB#93964: Detach One shot Agent from Manager - query results

---

.github/workflows/publish.rquest-omop-agent.yml
.github/workflows/release.rquest-omop-agent.yml

- Workflow to publish a timestamped docker image of the "one-shot" rquest omop agent
- Workflow for stable release of dockerised agent
- AB#94473
- AB#94474

AB#94466: rquest-omop-agent docker image github workflows

---

app/HutchManager/Models/User/UserModel.cs
app/HutchManager/Services/UserService.cs
app/manager-frontend/src/pages/User/list.jsx

- Add isProtected flag to UserModel,
- Set it to true for admin account in List action
- Check isProtected flag in the frontend and disable delete button if true
- AB#89067
- AB#89068
- AB#89066
- AB#89069

AB#89065: Disallow admin account deletion

---

lib/ROCrates.Net.Tests/TestDataset.cs
lib/ROCrates.Net/Models/ComputationalWorkflow.cs
lib/ROCrates.Net/Models/ContextEntity.cs
lib/ROCrates.Net/Models/DataEntity.cs
lib/ROCrates.Net/Models/Dataset.cs
lib/ROCrates.Net/Models/Entity.cs
lib/ROCrates.Net/Models/File.cs
lib/ROCrates.Net/Models/FileOrDir.cs
lib/ROCrates.Net/Models/Metadata.cs
lib/ROCrates.Net/Models/Person.cs
lib/ROCrates.Net/Models/RootDataset.cs
lib/ROCrates.Net/Models/SoftwareApplication.cs
lib/ROCrates.Net/Models/Workflow.cs
lib/ROCrates.Net/Models/WorkflowDescription.cs
lib/ROCrates.Net/ROCrate.cs

Created the following entities for RO-Crates:
- Person
- Metadata
- Entity
- FileOrDir
- File
- Dataset
- RootDataset
- ComputationalWorkFlow
- Workflow
- WorkflowDescription
- SoftwareApplication
- AB#98468
- AB#98496
- AB#98579
- AB#98581
- AB#98582
- AB#98583
- AB#98597
Models will need custom serialisation built. 
These entities are just a minimal set needed to finish building the main `ROCrate` class. Others like `TestSuite`, etc. will come later.

AB#98448: Remaining ROCrate Entities

---

lib/ROCrates.Net.Tests/TestEntity.cs
lib/ROCrates.Net.Tests/TestRoCrate.cs
lib/ROCrates.Net/Models/Entity.cs
lib/ROCrates.Net/Models/Part.cs
lib/ROCrates.Net/ROCrate.cs

Add generic `Add` method to `ROCrate.cs` which can add any Entity subclass.
Add builder methods to `ROCrate.cs` for `Person`, `Dataset`, `ComputationalWorkflow` and `File`.
- AB#98455
- AB#98596
- AB#98457
- AB#98456
- AB#98895
- AB#98453

AB#98445: ROCrate builder methods

---

lib/ROCrates.Net.Tests/TestFile.cs

Test was failing due to incorrect setup resulting in a race condition between tests for a file. Created fixture to be shared between all tests in `TestFile`.
- AB#99132
- AB#99133

AB#98840: File entity cannot write to destPath

---

lib/ROCrates.Net.Tests/TestDataset.cs
lib/ROCrates.Net.Tests/TestFile.cs

Fix a similar bug to #164 and #163. When running all tests, path clashes still caused the tests to unexpectedly fail to to path collision in chosen test base paths. Paths no longer collide.
- AB#99652
- AB#99656

AB#99610: File and Dataset test suites still occasionally fail

---

lib/ROCrates.Net.Tests/TestFileOrDir.cs
lib/ROCrates.Net.Tests/TestRoCrate.cs
lib/ROCrates.Net/Models/ComputationalWorkflow.cs
lib/ROCrates.Net/Models/ComputerLanguage.cs
lib/ROCrates.Net/Models/ContextEntity.cs
lib/ROCrates.Net/Models/Dataset.cs
lib/ROCrates.Net/Models/Entity.cs
lib/ROCrates.Net/Models/File.cs
lib/ROCrates.Net/Models/FileOrDir.cs
lib/ROCrates.Net/Models/Metadata.cs
lib/ROCrates.Net/Models/TestDefinition.cs
lib/ROCrates.Net/ROCrate.cs

Rename `Identifier` prop to `Id` for all Entities. Add own `Identifier` prop to `ComputerLanguage` because it's meant to have one.
- AB#99645
- AB#99647
- AB#99766

AB#99486: this.Identifier is different to this.Id in entities. Create Id field

---

lib/ROCrates.Net.Tests/TestFile.cs
lib/ROCrates.Net.Tests/TestFileOrDir.cs
lib/ROCrates.Net/Models/File.cs
lib/ROCrates.Net/Models/FileOrDir.cs

File entities were not saving with their extensions in the `@id` tags. This fix corrects that.
- AB#101862
- AB#101863
A unit test relating to saving files to the same place was discovered in while investigating this bug. A fix for that is also in this PR.

AB#101861: FileOrDir and subclass Id resolution is incorrect

---

app/HutchAgent.Tests/TestCrateMergeService.cs
app/HutchAgent.Tests/TestWfexsJobService.cs
app/HutchAgent/Program.cs
app/HutchAgent/Services/CrateMergerService.cs
app/HutchAgent/Services/MinioService.cs
app/HutchAgent/Services/WatchFolderService.cs
app/HutchAgent/Services/WfexsJobService.cs

Result RO-Crates can be merged into the input RO-Crate. The metadata of the input RO-Crate is modified to include the the zipped result crate. The merged file is save to S3.
- AB#104220
- AB#104222
- AB#104221
- AB#104225

AB#94504: Merge WfExS output crate into parent crate

---

app/HutchAgent/HostedServices/WatchFolderHostedService.cs
app/HutchAgent/Program.cs

Check if a job is finished before attempting to upload to the results store.
- AB#107264
- AB#107265

AB#107048: WatchFolder should check a job is finished first

---

app/HutchAgent/Config/JobPollingOptions.cs
app/HutchAgent/Data/Entities/WfexsJob.cs
app/HutchAgent/HostedServices/JobPollingHostedService.cs
app/HutchAgent/HostedServices/WatchFolderHostedService.cs
app/HutchAgent/Migrations/20230530141658_AddWfexsJobPid.Designer.cs
app/HutchAgent/Migrations/20230530141658_AddWfexsJobPid.cs
app/HutchAgent/Program.cs
app/HutchAgent/Services/WorkflowTriggerService.cs

- Remove provenance crate creation
- Stop looking for WfExS Run name after it's found
- Convert Watch Folder service to Job Polling service that detects finished jobs by PID
- Uploading and merging of results looks for execution crate
- Upon job execution and determination of the run name, the agent detaches from the process to start another job
- AB#108609
- AB#108610
- AB#108611
- AB#108612
- AB#108615
- AB#108782
- AB#108616
The execution crate is renamed from `execution.crate.zip` to `{run ID}.zip` so it unique when uploaded to results store.

AB#107058: WfExS trigger threading etc.

---

docker-compose.yml
website/docs/users/getting-started/configuration/nginx.md

Documentation for setting up a TRE to look for WorkflowHub workflows locally instead of over the internet.
- AB#108960
- AB#108963
- AB#108964
- AB#108961
The branch name is docker-redirects because I started on that then switched to workflows. The docker stuff will be in a separate PR.

AB#108952: Use Reverse Proxy for Workflows (e.g. WorkflowHub) -> Nexus

---

workflows/rquest-oneshot.cwl
workflows/rquest-oneshotx86.cwl

Use Docker Hub images for `rquest-omop-agent` since the Github ones are private and we can't change the permissions.
- AB#113152
- AB#113153
- AB#113154
- AB#113156

AB#113151: Can't pull rquest-omop-worker from GH repo

---

website/docs/users/getting-started/configuration/docker-hub-spoof.md

Documentation on how to set up `podman` to work with an air-gapped registry.
- AB#113666
- AB#113667
- AB#113668
- AB#113669
- AB#113670

AB#113477: Explore podman + wfexs

---

lib/ROCrates.Net.Tests/Fixtures/test-compound-types.json
lib/ROCrates.Net.Tests/Fixtures/test-invalid-metadata.json
lib/ROCrates.Net.Tests/TestDataset.cs
lib/ROCrates.Net.Tests/TestFileOrDir.cs
lib/ROCrates.Net.Tests/TestMetadata.cs
lib/ROCrates.Net.Tests/TestPreview.cs
lib/ROCrates.Net.Tests/TestRoCrate.cs
lib/ROCrates.Net/Exceptions/CrateReadException.cs
lib/ROCrates.Net/Exceptions/MetadataException.cs
lib/ROCrates.Net/Models/Dataset.cs
lib/ROCrates.Net/Models/Metadata.cs
lib/ROCrates.Net/ROCrate.cs

- `ROCrate` objects can now be initialised from an existing crate using the `Initialise` method.
- A directory can be converted to an RO-Crate using the `Convert` method.
- Removed constructor with arguments from `ROCrate`.
- Fixed tests that depended on `ROCrate` constructor with arguments.
- AB#113765
- AB#113766
- AB#113769
- AB#113767
- AB#113770
- AB#113771
- AB#114150

AB#98893: Initialising RO-Crates

---

lib/ROCrates.Net.Tests/TestDataset.cs
lib/ROCrates.Net.Tests/TestFileOrDir.cs
lib/ROCrates.Net/Models/Dataset.cs
lib/ROCrates.Net/Models/File.cs
lib/ROCrates.Net/Models/FileOrDir.cs

Make sure `@id` tags for dataset comes out as the given path (relative to the create root) with a slash (`/`) at the end.
- AB#114640
- AB#114641
- AB#114642

AB#114638: Dataset @id not being set properly

---

lib/ROCrates.Net.Tests/TestRoCrate.cs
lib/ROCrates.Net/ROCrate.cs

`ROCrate.Convert` now makes all `@id` tags relative to the crate root. So `path/to/file.txt` will have an `@id` of `path/to/file.txt`, where previously it was just `file.txt`.
- AB#114964
- AB#114965
- AB#114966

AB#114963: ROCrate.Convert must make all file and directory `@id`s relative to crate root

---

app/HutchAgent/Services/WfexsJobService.cs

- A Wfexs job **`Pid`** will be updated when updating the passed the job.
- List of Wfexs jobs will now include job **`Pid`** property, which polling service can use to check the process status and update the job **`RunFinished`** property.
- AB#115972
- AB#115973
- AB#115974

AB#115971: Update the Pid property when updating a Wfexs job and include the Pid property in the jobs list

---

app/HutchAgent.Tests/TestCrateMergeService.cs
app/HutchAgent/Config/PublisherOptions.cs
app/HutchAgent/HostedServices/JobPollingHostedService.cs
app/HutchAgent/Program.cs
app/HutchAgent/Services/CrateMergerService.cs

- Updated the **`UpdateMetadata`** method of **`CrateMergerService`** which now:
- adds **`publisher`** property based on publisher config to the root data entity
- adds **`publishedDate`** after the final metadata update
- Updated relevant test methods.
- AB#109781
- AB#109790
- AB#116730
_**`_pathToOutputDir`** in **`CrateMergerService`** might need to be updated in the future._

AB#108987: Add publisher and datePublished to the root data entity

---

ansible/playbook.yml
ansible/playbooks/files/install-podman4.sh
ansible/playbooks/install-docker.yml
ansible/playbooks/install-podman.yml
ansible/playbooks/set-up-ssl.yml
ansible/playbooks/set-up-vm.yml
ansible/playbooks/wfexs.yml

Added ansible playbook for installing podman 4.x rather than the default 3.x on Ubuntu.
Added fixes for:
- Making sure non root user can run docker
- Not using root where unnecessary
- Using ansible's magic variables for the remote user home and username
- AB#124118
- AB#124119
- AB#124120
- AB#124121

AB#123923: Ansible for podman

---

app/HutchAgent.Tests/TestCrateService.cs
app/HutchAgent/HostedServices/QueuePollingHostedService.cs
app/HutchAgent/Program.cs
app/HutchAgent/Services/CrateService.cs
app/HutchAgent/Services/FinalisationService.cs
app/HutchAgent/Services/WorkflowJobService.cs

Create new `FinalisationService` to handle post-execution steps of workflow runs.
The service handles updating the the job state in the local database, merging run outputs back to the input crate, updating the metadata of the crate, rewriting the bagit checksums, and uploading to the results store.
- AB#124796
- AB#124797
- AB#124798
- AB#124799
- AB#124800
- AB#124908
- AB#124909
- AB#124910

AB#124761: Refactor post execution checks

---

app/HutchAgent/HostedServices/QueuePollingHostedService.cs
app/HutchAgent/Program.cs
app/HutchAgent/Services/ExecuteActionHandler.cs
app/HutchAgent/Services/FinaliseActionHandler.cs

Add IOptions to ExecuteActionHandler and FinaliseActionHandler (renamed from FinalisationService).
- AB#126150
- AB#126152
- AB#126153

AB#126039: Not using IOptions in ExecuteActionHandler and FinaliseActionHandler

---

ansible/playbooks/set-up-vm.yml

Install .NET 7 with ansible as well as entity framework.
- AB#125998
- AB#125999
- AB#126000

AB#125997: Set ansible to include dotnet 7 and EF

---

.github/workflows/deploy.docs-website.yml

This PR changes the docs workflow to run when there are changes to HutchAgent as well as to the website source, so that Swagger changes are as up to date as possible.
- CI config changes only

AB#130446: docs build runs on dotnet changes for swagger

---

app/HutchAgent/appsettings.json
website/docs/getting-started/configuration/agent.md

This PR adds default port configuration into Hutch's `appsettings.json`.
Obviously it can still be overridden through the typical configuration means.
However, putting it into `appsettings.json`:
- explicitly tends to the expected typical use case of an airgapped environment, in which ports 80/443 are not suitable to bind on
- defaults to binding Hutch on public interfaces, not just localhost, tending to the expected typical use case
- serves as an example configuration for those wishing to modify the config, saving googling or referring to ASP.NET specific docs. 
- config and docs changes only

AB#130477: Default ports

---

DummyControllerApi/Config/EgressBucketDetailsOptions.cs
DummyControllerApi/Controllers/SubmissionController.cs
DummyControllerApi/DummyControllerApi.csproj
DummyControllerApi/Models/EgressBucketResponseModel.cs
DummyControllerApi/Models/FilesReadyRequestModel.cs
DummyControllerApi/Models/HutchApprovalRequestModel.cs
DummyControllerApi/Models/UpdateStatusResponseModel.cs
DummyControllerApi/Program.cs
DummyControllerApi/Properties/launchSettings.json
DummyControllerApi/Services/EgressApprovalHostedService.cs
DummyControllerApi/Services/InMemoryApprovalQueue.cs
DummyControllerApi/appsettings.Development.json
DummyControllerApi/appsettings.json
Hutch.sln
app/HutchAgent/Models/ControllerApi/FilesReadyForReviewRequest.cs
app/HutchAgent/Services/ControllerApiService.cs
app/HutchAgent/appsettings.Development.json

This PR adds a development only "Dummy Controller Api" app that can be used for testing Hutch outside of standalone mode.
It is not even close to a complete TRE Controller API implementation; it only implements the endpoints Hutch interacts with upstream and, for convenience, the downstream call to hutch's `jobs/approval` endpoint.
It requires token auth (to aid testing) but does no validation of provided tokens, to eliminate the need for a full oidc configuration.
It does some basic request validation, but otherwise its only job is to get the endpoint interfaces and response payloads correct to keep Hutch happy.
It keeps no persistent state and so doesn't care about accurate submission id's.
Hutch must be configured for OIDC so that it can get tokens for use in Controller API calls.
It …

AB#131635: Dummy controller api

---

app/HutchAgent/Config/WorkflowTriggerOptions.cs
app/HutchAgent/HutchAgent.csproj
app/HutchAgent/Models/JobQueue/InitiateEgressPayloadModel.cs
app/HutchAgent/Models/JobQueue/JobQueueMessage.cs
app/HutchAgent/Services/ActionHandlers/ExecuteActionHandler.cs
app/HutchAgent/Services/ActionHandlers/FetchAndExecuteActionHandler.cs
app/HutchAgent/Services/ActionHandlers/FinalizeActionHandler.cs
app/HutchAgent/Services/ActionHandlers/InitiateEgressActionHandler.cs
app/HutchAgent/Services/Contracts/IActionHandler.cs
app/HutchAgent/Services/Hosted/JobActionQueuePoller.cs
app/HutchAgent/Services/WorkflowTriggerService.cs
website/docs/development/partial-running.md
website/docs/getting-started/configuration/agent.md

This PR primarily adds the ability to skip workflow execution and substitute a static output crate from a path on disk.
This can be incredibly useful in dev/test when working on areas of Hutch that do not depend on a genuine execution itself, but require an output (e.g. lots of post-execution functionality).
Also documented some of the ways in which Hutch can be run and tested without the full stack present and configured.
Also accidentally fixed container deletion in outputs.
- AB#130929 - output container deletion
- Not adding unit testable code

AB#131740: Workflow Execution skipping

---

app/HutchAgent/Controllers/JobsController.cs
app/HutchAgent/Models/SubmitJobModel.cs
website/docs/development/index.md
website/docs/development/partial-running.md
website/docs/external-systems/minio/minio-keycloak.md
website/docs/getting-started/index.md
website/docs/getting-started/installation/agent.md

This PR updates some terminology in the docs, particularly around the TRE-FX stack, and also some boundary cases between the TRE Controller language "submission" and the Hutch language "job".
Hutch's `/jobs` submission payload has changed to use the TRE Controller `subId` form rather than `jobId` for consistency.
- non functional changes only

AB#131017: Terminology updates

---

app/HutchAgent/HutchAgent.csproj
app/HutchAgent/Program.cs
app/HutchAgent/Services/ActionHandlers/FinalizeActionHandler.cs
app/HutchAgent/Services/WorkflowTriggerService.cs
app/HutchAgent/Utilities/FileSystemUtility.cs
test/HutchAgent.Tests/FileSystemUtilityTests/TestSelectivelyDelete.cs
test/HutchAgent.Tests/HutchAgent.Tests.csproj

This PR changes output container deletion so that we only delete the images but retain metadata.

AB#131799: when containers are deleted from ouputs, we retain metadata files
